### ISSUE TITLE
aur source mistake

### ISSUE THREAD

**Issue by Sketch98** [recolic/vivado-wrapper#4]
the newest release is at https://github.com/recolic/vivado-wrapper/releases/download/v1.6/ **vivado-wrapper-1.6**.tar.gz.sig, not https://github.com/recolic/vivado-wrapper/releases/download/v1.6/ **v1.6**.tar.gz.sig

**Comment by recolic** [comment]
got it. I will look into it soon.

Feb 4, 2022 16:36:04 Nathan Sketch ***@***.***>:

**Comment by recolic** [comment]
Cleaning up old issue.

fixed by renaming the github release filename.
